<?
$carro = $cp->getCSec()->carro;
?>
<script src="/js/carro.js" type="text/javascript"></script>
<div id="inner">
    <? if($carro->N_PRODUCTOS > 0) { ?>
        <div class="top-nav">
        <? if($carro->ESTADO_CARRO == 0) { ?>
            <a class="btn btn-success bloqdes" style="color:white;">Confirmar<i class="icon-arrow-right icon-white icon-right"></i></a>
        <? } else { ?>
            <a class="bloqdes">< Volver al Paso 1</a>
            <form action="/cgi-bin/tbk_bp_pago.cgi" method="post" style="display:inline-block">
                <input name="TBK_MONTO" type="hidden" id="TBK_MONTO" value="<?=$carro->MONTO_CARRO?>00" />
                <input name="TBK_ID_SESION" type="hidden" id="TBK_ID_SESION" value="<?=$carro->ID_CARRO?>" />
                <input name="TBK_ORDEN_COMPRA" type="hidden" id="TBK_ORDEN_COMPRA" value="<?=$carro->ID_CARRO?>" />
                <input name="TBK_TIPO_TRANSACCION" type="hidden" id="TBK_TIPO_TRANSACCION" value="TR_NORMAL" />
                <input name="TBK_URL_EXITO" type="hidden" id="TBK_URL_EXITO" value="http://dev.lokiero.cl/exito" />
                <input name="TBK_URL_FRACASO" type="hidden" id="TBK_URL_FRACASO" value="http://dev.lokiero.cl/fracaso" />
                <input type="submit" class="btn btn-success" id="btnPagarTop" value="Pagar $<?=$carro->MONTO_CARRO_H?>"/>
            </form>
        <? } ?>
        </div>
    <? } ?>
    <h1>Carro de compra</h1>
    <? if($carro->N_PRODUCTOS > 0) { ?>
    <p>Estos son los productos que tienes actualmente en tu carro de compra.</p>
    <table class='table table-striped table-bordered' id='carro'>
        <thead>
            <tr>
                <th>Producto</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Total</th>
                <? if($carro->ESTADO_CARRO == 0) { ?>
                    <th class="actionCol red"></th>
                <? } ?>
            </tr>
        </thead>
        <tbody>
            <? for($i=0; $i<$carro->N_PRODUCTOS; $i++) { ?>
            <? $prod = $carro->PRODUCTOS[$i]; ?>
            <tr id_carro_prod="<?=$prod->ID_CARRO_PROD?>">
                <td title="<?=$prod->NOM_PRODUCTO?> <?=($prod->ESTADO_PRODUCTO==0)?" - Sin Stock":""?>" class="<?=($prod->ESTADO_PRODUCTO==0)?"red":""?>"><img src="/producto/<?=$prod->URL_IMAGEN?>" border="0" height="15" style="margin-right:5px;"/><?=$prod->NOM_PRODUCTO?></td>
                <td class="<?=($prod->ESTADO_PRODUCTO==0)?"red":""?>">$<?=$prod->PRECIO_CARRO_PROD_H?></td>
                <td class="<?=($prod->ESTADO_PRODUCTO==0)?"red":""?>"><?=$prod->CANTIDAD_CARRO_PROD?></td>
                <td class="<?=($prod->ESTADO_PRODUCTO==0)?"red":""?>">$<?=$prod->PRECIO_TOTAL_CARRO_PROD_H?></td>
                <? if($carro->ESTADO_CARRO == 0) { ?>
                    <td class="actionCol"><a href="#" title="Quitar del carro" class="tp delete"><i class="icon-remove"></i></a></td>
                <? } ?>
            </tr>
            <? } ?>
        </tbody>
    </table>
    <div class="top-nav">
    <? if($carro->ESTADO_CARRO == 0) { ?>
        <a class="btn btn-success bloqdes" style="color:white;">Confirmar<i class="icon-arrow-right icon-white icon-right"></i></a>
    <? } else { ?>
        <a class="bloqdes">< Volver al Paso 1</a>
        <form action="/cgi-bin/tbk_bp_pago.cgi" method="post" style="display:inline-block">
            <input name="TBK_MONTO" type="hidden" id="TBK_MONTO" value="<?=$carro->MONTO_CARRO?>00" />
            <input name="TBK_ID_SESION" type="hidden" id="TBK_ID_SESION" value="<?=$carro->ID_CARRO?>" />
            <input name="TBK_ORDEN_COMPRA" type="hidden" id="TBK_ORDEN_COMPRA" value="<?=$carro->ID_CARRO?>" />
            <input name="TBK_TIPO_TRANSACCION" type="hidden" id="TBK_TIPO_TRANSACCION" value="TR_NORMAL" />
            <input name="TBK_URL_EXITO" type="hidden" id="TBK_URL_EXITO" value="http://dev.lokiero.cl/exito.php" />
            <input name="TBK_URL_FRACASO" type="hidden" id="TBK_URL_FRACASO" value="http://dev.lokiero.cl/fracaso.php" />
            <input type="submit" class="btn btn-success" id="btnPagarTop" value="Pagar $<?=$carro->MONTO_CARRO_H?>"/>
        </form>
    <? } ?>
    </div>
    <div class="clear"></div>
    <? } else { ?>
    <p>No tienes productos en el carro.</p>
    <? } ?>
</div>