<?
$vn = $cp->getCSec()->vn;
$resumen = $cp->getCSec()->resumen;
$ca = $cp->getCSec()->ca;
$wp = $cp->getCSec()->wp;
$prod = $cp->getCSec()->prod;
$nProd = $cp->getCSec()->nProd;
$bidTotal = 0;
?>
<div id="inner">
    <h1>Compra exitosa!</h1>
    <div id="cuerpo">
        <p>Estimado <b><?=$_SESSION["NOM_USUARIO"]?></b>, la venta se realizo correctamente y se cargaron <?=$resumen->totalBid?> Bids a tu cuenta.</p>
        <h2>Detalle de la compra</h2>
        <div class="row">
            <div class="span5">
                <table class='table table-striped table-bordered'>
                    <tr>
                        <td>Fecha de compra:</td>
                        <td><?=date("d-m-Y")?></td>
                    </tr>
                    <tr>
                        <td>Orden de compra:</td>
                        <td><?=$ca->ID_CARRO?></td>
                    </tr>
                    <tr>
                        <td>Codigo de autorizaci&oacute;n:</td>
                        <td><?=$wp->Tbk_Codigo_Autorizacion?></td>
                    </tr>
                    <tr>
                        <td>N&uacute;mero de tarjeta:</td>
                        <td>xxxxxxxxxxxxx-<?=$wp->Tbk_Final_numero_Tarjeta?></td>
                    </tr>
                    <tr>
                        <td>Cantidad de Cuotas:</td>
                        <td>0<?=$wp->Tbk_Numero_Cuotas?></td>
                    </tr>
                    <tr>
                        <td>Tipo de Cuotas:</td>
                        <td><?=$vn?></td>
                    </tr>
                    <tr>
                        <td>Comercio:</td>
                        <td>Lo Kiero! (<a href="/">www.lokiero.cl</a>)</td>
                    </tr>
                </table>
            </div>
            <div class="span6">
                <table class='table table-striped table-bordered' id='carro'>
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th class="blue">Total</th>
                            <th class="blue">Total Bids</th>
                        </tr>
                    </thead>
                    <tbody>
                        <? 
                        for($i=0; $i<$nProd; $i++) { 
                            $pro = $prod[$i];
                            $bidFila = $pro->CANTIDAD_CARRO_PROD * $pro->VALOR_BID;
                            $bidTotal += $bidFila;
                        ?>
                        <tr>
                            <td><img src="/producto/<?=$pro->URL_IMAGEN?>" border="0" height="15" style="margin-right:5px;"/><?=$pro->NOM_PRODUCTO?></td>
                            <td>$<?=number_format($pro->PRECIO_CARRO_PROD, 0, ",", ".")?></td>
                            <td><?=$pro->CANTIDAD_CARRO_PROD?></td>
                            <td>$<?=number_format($pro->CANTIDAD_CARRO_PROD*$pro->PRECIO_CARRO_PROD, 0, ",", ".")?></td>
                            <td><?=$bidFila?></td>
                        </tr>
                        <? } ?>
                        <tr>
                            <td colspan="2" style="text-align: right;">Total</td>
                            <td><?=$resumen->totalProd?></td>
                            <td>$<?=number_format($resumen->totalMonto, 0, ",", ".")?></td>
                            <td><?=$resumen->totalBid?></td>
                        </tr>
                    </tbody>
                </table>
                <p><b>Nota</b>: Todos los montos expresados corresponde a pesos chilenos, IVA incluido. Para devoluciones y/o reclamos revisa los <a href="/terminos">terminos y condiciones</a> o comunicate con el departamento de <a mailto="ventas@lokiero.cl">Ventas</a></p>
            </div>
        </div>
    </div>
</div>