<div id="inner">
    <h1>Transacci&oacute;n fracasada :(</h1>
    <div id="cuerpo"><p>Lamentablemente la orden de compra N° <?=$_POST["TBK_ORDEN_COMPRA"]?> no pudo ser procesada, las posibles causas de este rechazo son:</p>
        <ul>
            <li>Error en el ingreso de los datos de su tarjeta de cr&eacute;dito (fecha y/o c&oacute;digo de seguridad).</li>
            <li>Su tarjeta de cr&eacute;dito no cuenta con el cupo necesario para cancelar la compra.</li>
            <li>Tarjeta a&uacute;n no habilitada en el sistema financiero.</li>
            <li>Si el problema persiste favor comunicarse con su Banco emisor.</li>
        </ul>
    </div>
</div>