<?
function getSelect($obj, $val, $id, $nom, $sel=null, $onChange=null) {
    $r = "<SELECT name='$nom' id='$nom' onChange=\"".$onChange."\" class='chzn-select' style='width:220px'>";
    foreach($obj as $o) {
        if($sel!=null && $o->$id==$sel) {
            $r .= "<OPTION value='".trim($o->$id)."' selected>".utf8_encode($o->$val)."</OPTION>";
        } else {
            $r .= "<OPTION value='".trim($o->$id)."'>".utf8_encode($o->$val)."</OPTION>";
        }
    }
    $r .= "</SELECT>";
    return $r;
}

$inv = $cp->getCSec()->res;
$nInv = count($inv);
?>
<!--<link rel="stylesheet" href="css/chosen.css" type="text/css" />-->
<!--<script type="text/javascript" src="js/chosen.jquery.min.js"></script>-->
<script src="/js/invitacion.js" type="text/javascript"></script>
<div id="inner">
    <h1>Bienvenido!</h1>
    <p>Todos estos amigos te invitaron, pero ¿a quien quieres dar los bids por haberlo hecho?</p>
    <form style="width: 400px; margin-top: 10px;" id="formu" action="/?sec=invitacion&do=aceptar">
        <ul class="invitacionUsuarios">
            <? for($i=0; $i<$nInv; $i++) { ?>
            <? $in = $inv[$i]; ?>
            <li class="mano"><label><input type="radio" name="id_request" class="id_request" value="<?=$in->ID_REQUEST?>" style="display: inline-block; margin-right: 5px;" <?=($i==0)?"checked":""?>/>
                    <img src="https://graph.facebook.com/<?=$in->ID_FROM?>/picture" height=39/>
                    <span class="nom"><?=$in->NOM_USUARIO?> <?=$in->APE_USUARIO?></span>
                    <span class="fecha"><?=$in->FECHA_REQUEST_H?></span></label>
            </li>
            <? } ?>
        </ul>
        <input type="submit" value="Listo!" class="btn btn-success" id="btnGuardar" style="margin-left: 55px;"/>
        <p class="msg"></p>
        <div class="clear"></div>
    </form>
</div>
<script>
//    ko.applyBindings(new InvitacionesViewModel(<?=$inv->MODELO->INVITACION_DISP?>, <?=$inv->MODELO->INVITACION_USADA?>, <?=($inv->MODELO->INVITACION_USADA>0)?json_encode($inv->INVITACIONES):"[]"?>));
</script>