<?
function getSelect($obj, $val, $id, $nom, $sel=null, $onChange=null) {
    $r = "<SELECT name='$nom' id='$nom' onChange=\"".$onChange."\" class='chzn-select' style='width:220px'>";
    foreach($obj as $o) {
        if($sel!=null && $o->$id==$sel) {
            $r .= "<OPTION value='".trim($o->$id)."' selected>".utf8_encode($o->$val)."</OPTION>";
        } else {
            $r .= "<OPTION value='".trim($o->$id)."'>".utf8_encode($o->$val)."</OPTION>";
        }
    }
    $r .= "</SELECT>";
    return $r;
}

$inv = $cp->getCSec()->inv;
?>
<link rel="stylesheet" href="css/chosen.css" type="text/css" />
<script type="text/javascript" src="js/chosen.jquery.min.js"></script>
<script src="/js/invitacion.js?15052012" type="text/javascript"></script>
<div class="top-nav">
    <a class="btn btn-success <?=($inv->MODELO->INVITACION_DISP>0)?"":"disabled"?>" id="btnInvitar" data-bind="click: invitar, html: inv_texto, css: {'disabled': disInvitar}">Invita más amigos (<?=$inv->MODELO->INVITACION_DISP?>)</a>
</div>
<h1>Invitaciones</h1>
<div class="inner">
    <p>Invita a tus amigos y gana 2 bids por cada uno que se registre!</p>
<!--    <pre><?print_r($inv)?></pre>-->
    <? //if($inv->MODELO->INVITACION_USADA>0) { ?>
    <table class='table table-striped table-bordered' id='invitaciones' data-bind="fadeVisible: hasSentInvitaciones">
        <thead>
            <tr>
                <th>Para</th>
                <th>Fecha de envio</th>
                <th>Estado</th>
                <th class="actionCol"></th>
            </tr>
        </thead>
        <tbody data-bind="foreach: inv">
            <? //for($i=0; $i<$inv->MODELO->INVITACION_USADA; $i++) { ?>
            <? //$iAux = $inv->INVITACIONES[$i]; ?>
            <tr>
                <td data-bind="text: $data.NOM_TO"></td>
                <td data-bind="text: $data.FECHA_REQUEST_H"></td>
                <td data-bind="text: $data.ESTADO_INVITACION_H"></td>
                <td class="actionCol">
                    <? //if($iAux->ESTADO_INVITACION == 0) { ?>
                    <a class="delete" data-bind="click: $parent.del, visible: $data.ESTADO_INVITACION==0"><img src="img/delete.png" title="Eliminar invitaci&oacute;n" class="tp" width="10"/></a>
                    <? //} ?>
                </td>
            </tr>
            <? //} ?>
        </tbody>
    </table>
    <? //} ?>
</div>
<script>
    ko.applyBindings(new InvitacionesViewModel(<?=$inv->MODELO->INVITACION_DISP?>, <?=$inv->MODELO->INVITACION_USADA?>, <?=($inv->MODELO->INVITACION_USADA>0)?json_encode($inv->INVITACIONES):"[]"?>));
</script>