<!DOCTYPE html>
<html  xmlns="http://www.w3.org/1999/xhtml"
       xmlns:og="http://ogp.me/ns#"
       xmlns:fb="http://www.facebook.com/2008/fbml">
    <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# lokiero: http://ogp.me/ns/fb/lokiero#">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta property="og:title" content="<?=$cp->getTitulo();?>"/>
        <meta property="og:type" content="<?=($cp->getCSec()->svip)?"lokiero:subasta":"website";?>" />
        <meta property="og:url" content="http://www.lokiero.cl/<?=($cp->getCSec()->svip)?"svip/".$cp->getCSec()->svip->COD_SUBASTA:""?>" />
        <meta property="og:image" content="http://www.lokiero.cl/<?=($cp->getCSec()->svip)?"producto/".$cp->getCSec()->svip->URL_IMAGEN:"img/logoFB.png"?>"/>
        <meta property="og:site_name" content="Lo Kiero!"/>
        <meta property="og:description" content='La nueva forma de comprar, al mejor precio, con descuentos de hasta un 90%!' />
        <meta property="fb:app_id" content="264213770284841"/>
        <script src="/js/jquery-1.7.min.js" type="text/javascript"></script>
<!--        <script src="/js/jquery.tmpl.min.js" type="text/javascript"></script>-->
        <script src="/js/jquery.validate.min.js" type="text/javascript"></script>
        <script src="/js/facebook.js?lala" type="text/javascript"></script>
        <script src="/js/knockout-2.0.0.js" type="text/javascript"></script>
        <script src="/js/jquery.bar.js" type="text/javascript"></script>
        <script src="/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/js/jquery.sharrre-1.2.0.min.js" type="text/javascript"></script>
        <script src="/js/base.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.css?lele" />
        <link rel="stylesheet" type="text/css" href="/css/estilos.css?lele2" />
        <title><?=$cp->getTitulo();?></title>
        <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-29417526-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

        </script>
<!--   Ini Invitacion-->
    <script id="invAcepta" type="text/x-jquery-tmpl">
        <p>Hola!,  <span id="nomEmi">${attributes.NOM_USUARIO} ${attributes.APE_USUARIO}</span> te invito a ser parte de LoKiero!, para aceptar la invitacion y registrarte haz <span id="acepta">click aqui</span></p>
    </script>
    <script id="invitacionUsuariosTmpl" type="text/x-jquery-tmpl">
        <div id="inner">
            <h1>Bienvenido!</h1>
            <p>Todos estos amigos te invitaron, pero ¿a quien quieres daras el premio por haberlo hecho?</p>
            <form style="width: 400px; margin-top: 10px;" id="formu">
            <ul class="invitacionUsuarios">
                {{each models}}
                <li class="mano"><label><input type="radio" name="id_request" class="id_request" value="${$value.attributes.ID_REQUEST}" /><img src="https://graph.facebook.com/${$value.attributes.ID_FROM}/picture" height=39/><span class="nom">${$value.attributes.NOM_USUARIO} ${$value.attributes.APE_USUARIO}</span><span class="fecha">${$value.attributes.FECHA_REQUEST}</span></label></li>
                {{/each}}
            </ul>
                <input type="submit" value="Guardar" class="btn btn-success pull-right" id="btnGuardar"/>
                <p class="msg"></p>
                <div class="clear"></div>
            </form>
        </div>
    </script>
    
    <script id="invitacionesTmpl" type="text/x-jquery-tmpl">
        <div id="inner">
            <div class="top-nav">
                <a class="btn btn-success {{if attributes.INVITACION_DISP <= 0}}disabled{{/if}}" id="btnInvitar">Invita más amigos (${attributes.INVITACION_DISP})<i class="icon-white icon-share-alt icon-right"></i></a>
            </div>
            <h1>Invitaciones</h1>
            <p>Invita a tus amigos y gana 2 bids por cada uno que se registre!</p>
            {{if attributes.INVITACION_USADA > 0}}
            <table class='table table-striped table-bordered' id='invitaciones'>
                <thead>
                    <tr>
                        <th>Para</th>
                        <th>Fecha de envio</th>
                        <th>Estado</th>
                        <th class="actionCol"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            {{/if}}
        </div>
    </script>
    
    <script id="invitacionFilaTmpl" type="text/x-jquery-tmpl">
        
            <td>${attributes.NOM_TO}</td>
            <td>${attributes.FECHA_REQUEST}</td>
            <td>
                {{if attributes.ESTADO_INVITACION == 0}} Enviada
                {{else}}
                    {{if attributes.ESTADO_INVITACION == 1}} Aceptada
                    {{else}} Rechazada
                    {{/if}}
                {{/if}}
            </td>
            <td class="actionCol">{{if attributes.ESTADO_INVITACION == 0}} <a href="#" id="delete"><img src="img/delete.png" title="Eliminar invitacion" clasnes="" width="10"/></a> {{/if}}</td>
        
    </script>
<!--    Fin Invitacion-->
    </head>
    <body>
        <div id="notificacion" style="display:none;"></div>
        <div id="contenedor">
            <div class="menu">
                <ul>
                    <li><a href="/">INICIO</a></li>
                    <li><a href="/quienes-somos">QUIÉNES SOMOS</a></li>
                    <li><a href="/bids">BIDS</a></li>
                    <li><a href="/terminos">TÉRMINOS Y CONDICIONES</a></li>
                    <li><a href="/faq">FAQ</a></li>
                    <li><a href="/contacto">CONTACTO</a></li>
                    <li><a href="https://www.facebook.com/LoKieroBid" style="padding: 0;"><img src="/img/fb_icon.png" width="30" style="float: left;margin-bottom: -10px;" class="tp" title="Siguenos en Facebook" data-placement="bottom"/></a></li>
                    <li><a href="https://twitter.com/lo_kiero" style="padding: 0;"><img src="/img/tw_icon.png" width="30" style="float: left;margin-bottom: -10px;"  class="tp" title="Siguenos en Twitter" data-placement="bottom"/></a></li>
                </ul>
            </div><!--fin menu -->
            <div id="encabezado">
                <div id="logo" class="tp" data-placement="right" title="Volver al inicio"><a href="/"><img src="/img/logo.png" width="366" height="131" border="0" /></a></div><!--fin logo -->
                <ul id="pestanas">
                    <? if($cp->isLoged) { ?>
                        <li id="registro" class="tp" title="<?=$cp->getSession()->get("NICK_USUARIO")?> tienes <?=$cp->usuario->BID_DISPONIBLE?> Bids para usar en las subastas"><a href='/micuenta'><span><?=$cp->usuario->BID_DISPONIBLE?> Bids</span><img src='https://graph.facebook.com/<?=$cp->user?>/picture' height=32 border=0/></a></li>
<!--                        <li id="invitar" class="tp" title="Invita a tus amigos y gana Bids por cada uno que se registre"><a href="/invitaciones">Invita y Gana <img src="/img/ki2_10.png" width="34" height="38" border="0"/></a></li>-->
                        <li id="compraBid" class="tp" title="Compra Bids para participar de las subastas"><a href="/bids">Compra Bids <img src="/img/BID.png" width="36" height="38" border="0"/></a></li>
                        <li id="carroCompra" class="tp" title="Tienes <?=$cp->carro->N_PRODUCTOS?> productos en tu carro de compra por un total de $<?=$cp->carro->MONTO_CARRO_H?>"><a href="/carro">Carro de compra (<?=$cp->carro->N_PRODUCTOS?>)</a></li>
                    <? } else { ?>
                        <li id="registro" class="tp" title="Registrate usando tu cuenta de Facebook"><a href="<?=$cp->loginUrl?>">Registrate! <img src="/img/ki2_12.png" width="36" height="38" /></a></li>
                    <? } ?>
                </ul>
            </div>
            <div id="contenido">
                <? include $cp->getCSec()->getLayout(); ?>
            </div>
            <? if($cp->sec == "main") { ?>
                <div id="flechas">
                    <div id="ahora">AHORA</div>
                </div>
            <? } ?>
            
            <div id="sombra"></div>
            <div>
                <img alt="¿Como participar?" title="¿Como participar?" src="/img/banner.png" style="margin-left: -25px;"/>
            </div>
        </div>
        <div id="pie">
            <div id="tarjetas"><img src="/img/ki3_40.png" width="743" height="100"></div>
            <p class="infoEmpresa"><b>Lo Kiero!</b>&#8482 (<a href="http://www.lokiero.cl">www.lokiero.cl</a>) - Av. 11 de septiembre 1881, of 1620, Providencia, Santiago, Chile</p>
        </div>
        <div id="fb-root"></div>
        <script>               
            window.fbAsyncInit = function() {
                FB.init({
                    appId: '264213770284841', 
                    cookie: true, 
                    xfbml: true,
                    oauth: true
                });
//                FB.Event.subscribe('auth.login', function(response) {
////                    window.location.reload();
//                    setSession(response);
//                });
                FB.Event.subscribe('auth.logout', function(response) {
//                    console.log("logout");
                    window.location = "/?sec=log&do=out";
//                    $registroBtn.click(conecta);
                });
                FB.getLoginStatus(function(response) {
//                    console.log("getLoginStatus");
                    var res = response;
//                    console.log(response);
                    if (response.authResponse) {
//                        window.location.reload();
//                        console.log("setSession");
                        setSession(response);
                    } else {
//                        console.log("logout");
                        <? if($cp->isLoged) { ?>
                        window.location = "/?sec=log&do=out";
                        <? } ?>
//                        $registroBtn.click(conecta);
//                        $registroBtn2.click(conecta);
                    }
                });
                $('#shareme').sharrre({
                    share: {
                        googlePlus: true,
                        facebook: true,
                        twitter: true,
                        digg: false,
                        delicious: false,
                        stumbleupon: false,
                        linkedin: false
                    },
                    buttons: {
                        googlePlus: {size: 'medium'},
                        facebook: {layout: 'button_count'},
                        twitter: {count: 'horizontal', via:'lo_kiero'}
                    },
                    enableHover: true,
                    enableCounter: false,
                    enableTracking: true
                });
            };
            (function() {
                var e = document.createElement('script'); e.async = true;
                e.src = document.location.protocol +
                '//connect.facebook.net/es_ES/all.js';
                document.getElementById('fb-root').appendChild(e);
            }());
//            ko.applyBindings(new baseViewModel('<?=$cp->getSession()->get("NICK_USUARIO")?>', <?=$cp->usuario->BID_DISPONIBLE?>, <?=$cp->carro->N_PRODUCTOS?>, '<?=$cp->carro->MONTO_CARRO_H?>'));
        </script>
        <div class='modal hide fade in' id="askNick">
            <div class='modal-header'>
                <h3>Bienvenido</h3>
            </div>
            <form id='nickForm' class='form-horizontal' style="margin:0;">
                <div class='modal-body'>
                    <p>Perfecto!, ahora solo falta el nombre con que quieres ser identificado</p>
                        <div class='control-group'>
                            <label class='control-label' for='username'>Nombre:</label>
                            <div class='controls'>
                                <input type='text' name='username' id='username' class='span3 required' value='' />
                            </div>
                        </div>
                </div>
                <div class='modal-footer'>
                    <p id='msg' class='feedback'></p>
                    <input type='submit' class='btn btn-primary' value='Guardar' id='btnGuardar'/>
                </div>
            </form>
        </div>
    </body>
</html>