<!DOCTYPE html>
<html  xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" href="css/base.css" />
    </head>
    <script id="subastaMiniTmpl" type="text/x-jquery-tmpl">
        <span id="tiempo">${attributes.RESTO_TIEMPO}</span>
        <span id="monto">$ ${attributes.MONTO_SUBASTA}</span>
        <span id="bidder">Neeph</span>
        <span id="producto"><a href="#!/subasta/${attributes.ID_SUBASTA}"><img src="producto/${attributes.IMG_PRODUCTO}" height="90"/></a></span>
        <span id="bid">
            <span id="costo-bid">${attributes.COSTO_BID_PESOS}</span>
            <span id="delay">${attributes.TIEMPO_RETRASO}"</span>
            <a class="bid-btn">BID</a>
        </span>
    </script>
    <script id="subastaTmpl" type="text/x-jquery-tmpl">
        <div class="subasta">
            <span id="tiempo">${attributes.RESTO_TIEMPO}</span>
            <span id="monto">$ ${attributes.MONTO_SUBASTA}</span>
            <span id="bidder">Neeph</span>
            <span id="producto"><img src="producto/${attributes.IMG_PRODUCTO}" width="290"/></span>
            <span id="bid">
                <span id="costo-bid">${attributes.COSTO_BID_PESOS}</span>
                <span id="delay">${attributes.TIEMPO_RETRASO}"</span>
                <a class="bid-btn">BID</a>
            </span>
        </div>
    </script>
    <body>
        <div id="header">
            <div id="header-wrapper">
                <span id="logo">Bid</span>
                <div id="user-info">
                    <div id="bid-info">
                        <span>Tienes 3 Bid disponibles</span>
                    </div>
                    <? $me = $cp->user_profile; ?>
                    <? if($me) { ?>
                    <div id="profile-info">
                        <img src="https://graph.facebook.com/<?php echo $me["id"]; ?>/picture" height="26" />
                        <span id="name"><?=$me["username"]."lalalal"?></span>
                        <div class="dropdown">
                            <ul>
                                <li><a href="#">Perfil</a></li>
                                <li><a href="#">Configuracion</a></li>
                                <li><a href="#">Salir</a></li>
                            </ul>
                        </div>
                    </div>
                    <? } ?>
                </div>
            </div>
        </div>
        <div id="wrapper">
            <div id="content">
                <? include $cp->getCSec()->getLayout(); ?>
            </div>
            <div id="sidebar">
                <div id="side-nav">
                    <h1>Sidebar</h1>
                    <pre>
                    <?print_r($_SESSION)?>
                    </pre>
                </div>
            </div>
            <div class="clear"></div>
            <div id="footer">
                <p><a href="http://notengoniuno.flawers.me/public/">No tengo ni $uno</a> | Desarrollado por <a href="http://twitter.com/#!/Neeph" class="yo">@Neeph</a> en sus ratos de ocio =)</p>
            </div>
        </div>
        <div id="aire"></div>
        <div id="fb-root"></div>
        <script>
            window.fbAsyncInit = function() {
                FB.init({
                    appId   : '<?php echo $cp->facebook->getAppId(); ?>',
                    status  : true, // check login status
                    cookie  : false, // enable cookies to allow the server to access the session
                    xfbml   : true // parse XFBML
                });
                FB.getLoginStatus(function(response) {
                    if (response.session) {
                        console.log("loged")
                    } else {
                        console.log("not loged");
                    }
                });
//                console.log(FB);
            };

            (function() {
                var e = document.createElement('script');
                e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
                e.async = true;
                document.getElementById('fb-root').appendChild(e);
            }());
        </script>
        <script src="js/LAB.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            $LAB
            .script("js/jquery-1.5.min.js").wait()
//            .script("js/jquery.easing.1.3.js")
            .script("js/jquery.tmpl.min.js")
            .script("js/underscore-min.js")
            .script("js/facebook.js")
            .script("js/backbone-min.js")
            .script("js/cacheprovider.js").wait()
            .script("js/CPrincipal.js");      
        </script>
    </body>
</html>