<?
$smain = $cp->getCSec()->smain;
?>
<script src="/js/main.js?26042012" type="text/javascript"></script>
<div class="subastaVipMain">
    <div class="imagen"><a href="/svip/<?=$smain->COD_SUBASTA?>"><img src="producto/<?=$smain->URL_IMAGEN?>" width="570"/></a></div>
    <div class="mensaje-top">
        <h3 style="display:inline-block; margin-right: 10px;">¿No sabes como ganar?</h3><a class="btn btn-warning" id="manual" href="#manual">Aprende ahora!</a>
    </div>
    <div id="descripcion">
        <div id="texto">
            <h1><a href="/svip/<?=$smain->COD_SUBASTA?>"><?=$smain->NOM_PRODUCTO?></a></h1>
            <div class="share">
                <div id="shareme" data-url="http://www.lokiero.cl/svip/<?=$smain->COD_SUBASTA?>" data-text="<?=$smain->NOM_PRODUCTO?> :: Lo Kiero!.cl - Subastas VIP"></div>
            </div>
            <ul>
                <? if($smain->ESTADO_SUBASTA == 0) { ?>
                <li id="dia" class="dia">El d&iacute;a <span class="verde bold grande sombra"><?=$smain->FECHA_SUBASTA?></span> a las <span class="verde bold grande sombra"><?=$smain->HRS_SUBASTA?>:<?=$smain->MIN_SUBASTA?></span> hrs</li>
                <? } else { ?>
                <li id="dia" class="dia">Ya comenz&oacute;!!</li>
                <? } ?>
                <? if($smain->ESTADO_SUBASTA == 0) { ?>
                <li id="entrada" class="tp entrada" data-placement="left" rel='twipsy' title="<?=($smain->BID_ENTRADA>0)?"Para ser parte de esta subasta debes pagar $".$smain->BID_ENTRADA." Bids":"Es GRATIS, ap&uacute;rate y reserva tu cupo AHORA!!"?>">Entrada: <span class="verde bold grande sombra"><?=($smain->BID_ENTRADA>0)?"$".$smain->BID_ENTRADA." Bids":"GRATIS!!"?></li>
                <? if($smain->RESTO_USUARIOS > 1) { ?>
                    <li data-bind="dot: ru_titulo, html: ru_texto" id="usuarios" class="tp usuarios" data-placement="left" rel='twipsy'>Faltan <?=$smain->RESTO_USUARIOS?> usuarios</li>
                <? } else if($smain->RESTO_USUARIOS > 0) { ?>
                        <li data-bind="dot: ru_titulo, html: ru_texto" id="usuarios" class="tp usuarios" data-placement="left" rel='twipsy' title="Un usuario más y la subasta podra realizarse">Solo falta <?=$smain->RESTO_USUARIOS?> usuario!</li>
                <? } else { ?>
                        <li data-bind="dot: ru_titulo, html: ru_texto" id="usuarios" class="tp usuarios" data-placement="left" rel='twipsy' title="Se alcanzó el minimo de usuarios para que la subasta se realice">Minimo alcanzado ;)</li>
                <? } ?>
                <? } ?>
            </ul>
        </div><!--fin texto -->
        <? if($cp->isLoged) { ?>
            <? if($smain->ESTADO_SUBASTA == 0) { ?>
            <? if($smain->IN_SUBASTA == 1) { ?>
                <a class="btn btn-primary btn-gigante tp" data-placement="left" rel='twipsy' title="Ya eres parte de la subasta, solo debes esperar a que comience!" id_subasta="<?=$smain->ID_SVIP?>" data-bind="click: reservar, html: res_texto, dot: res_titulo, css: {'disabled': is_disabled}">Ya esta Reservado!</a>
                <a class="negativo tp anular" data-placement="right" rel='twipsy' title="Anula tu reserva" id_subasta="<?=$smain->ID_SVIP?>" data-bind="click: anular, visible: in_subasta">Anular reserva</a>
            <? } else { ?>
                <? if($cp->like) { ?>
                <a class="btn btn-primary btn-gigante tp" data-placement="left" rel='twipsy' title="Reserva tu cupo para ser parte de la subasta!" id_subasta="<?=$smain->ID_SVIP?>" data-bind="click: reservar, html: res_texto, dot: res_titulo, css: {'disabled': is_disabled}"><b>RESERVA</b> TU CUPO!</a>
                <a class="negativo tp anular" data-placement="right" rel='twipsy' title="Anula tu reserva"  style="display:none;" id_subasta="<?=$smain->ID_SVIP?>" data-bind="click: anular, visible: in_subasta">Anular reserva</a>
                <? } else { ?>
                <a class="btn btn-primary btn-gigante tp" data-placement="left" title="Antes de reservar debes darle Me Gusta a nuestro Facebook" href="https://www.facebook.com/LoKieroBid" target="_blank">Visita nuestro <strong>Facebook</strong></a>
                <? } ?>
            <? } ?>
            <? } else if($smain->ESTADO_SUBASTA == 3 || $smain->ESTADO_SUBASTA == 1) { ?>
                <a href="/svip/<?=$smain->COD_SUBASTA?>" class="btn btn-primary btn-gigante tp" data-placement="left" rel='twipsy' title="Entra a la subasta y Gana!">Entra a la Subasta!</a>
            <? } ?>
        <? } else { ?>
            <a class="btn btn-primary btn-gigante tp" href="<?=$cp->loginUrl?>" id="registro2" data-placement="left" title="Usa tu cuenta de Facebook para registrarte!">Ingresa con tu <b>Facebook</b>!</a>
            <div class="fb-facepile" data-width="350" data-max-rows="2" data-size="large"></div>
        <? } ?>
    <!--[if IE]>
    <div style='margin-top: 40px;'>
    <h3 style="margin:0">Estas usando Internet Explorer :(</h3>
    <p>Para una mejor experiencia en las subastas te recomendamos usar:</p>
    <div style="text-align: center;">
    <a href="https://www.google.com/chrome" target="blank"><img src="/img/chrome.png" border="0" width="50"/></a>
    <a href="http://www.getfirefox.com" target="blank"><img src="/img/firefox.png" border="0" width="50"/></a>
    <a href="http://www.opera.com/download/" target="blank"><img src="/img/opera.png" border="0" width="50"/></a>
    <a href="http://www.apple.com/safari/download/" target="blank"><img src="/img/safari.png" border="0" width="50"/></a>
    </div>
    </div>
    <![endif]-->
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<script>
    ko.applyBindings(new SVipViewModel(<?=$smain->ID_SVIP?>, '<?=$smain->COD_SUBASTA?>', <?=($smain->IN_SUBASTA==1)?'true':'false'?>, <?=$smain->RESTO_USUARIOS?>));
</script>