<?
$smain = $cp->getCSec()->svip;
?>
<script src="/js/svip.js?26042012" type="text/javascript"></script>
<div class="subastaVip row">
    <div class="span6">
        <div class="imagen">
            <img src="/producto/<?=$smain->URL_IMAGEN?>" width="500"/>
        </div>
        <div class="fb-live-stream" data-event-app-id="264213770284841" data-width="500" data-height="600" data-xid="<?=$smain->COD_SUBASTA?>" data-via-url="http://www.lokiero.cl/svip/<?=$smain->COD_SUBASTA?>" data-always-post-to-friends="true"></div>
    </div>
    <div class="mensaje-top">
        <h3 style="display:inline-block; margin-right: 10px;">¿No sabes como ganar?</h3><a class="btn btn-warning" id="manual" href="#manual">Aprende ahora!</a>
    </div>
    <div id="descripcion" class="span6">
        <div id="texto">
            <h1><?=$smain->NOM_PRODUCTO?></h1>
            <div class="share">
                <div id="shareme" data-url="http://www.lokiero.cl/svip/<?=$smain->COD_SUBASTA?>" data-text="<?=$smain->NOM_PRODUCTO?> :: Lo Kiero!.cl - Subastas VIP"></div>
            </div>
            <span id="tiempo" data-bind="text: tiempo_texto, style: {color: resto_tiempo_sec() < 10 ? 'red':'black'}">
                <? if($smain->RESTO_TIEMPO_SEC < 0) { ?>
                    Terminada!
                <? } else { ?>
                    <?=$smain->RESTO_TIEMPO?>
                <? } ?>
            </span>
            <span id="monto" data-bind="text: texto_monto_subasta">$ <?=$smain->MONTO_SUBASTA?></span>
            <span id="bidder" data-bind="text: nick_usuario"><?=$smain->NICK_USUARIO?></span>
        </div>
        <? if($cp->isLoged && $smain->ESTADO_SUBASTA == 0) { ?>
            <? if($smain->ALLOW == 1) { ?>
                <a class="btn btn-primary btn-gigante tp" data-placement="left" rel='twipsy' title="Ya eres parte de la subasta, solo debes esperar a que comience!" id_subasta="<?=$smain->ID_SVIP?>" data-bind="click: reservar, html: res_texto, dot: res_titulo, css: {'disabled': is_reserva_disabled}">Ya esta Reservado!</a>
                <a class="negativo tp anular" data-placement="right" rel='twipsy' title="Anula tu reserva" id_subasta="<?=$smain->ID_SVIP?>" data-bind="click: anular, visible: in_subasta">Anular reserva</a>
            <? } else { ?>
                <? if($cp->like) { ?>
                <a class="btn btn-primary btn-gigante tp" data-placement="left" rel='twipsy' title="Reserva tu cupo para ser parte de la subasta!" id_subasta="<?=$smain->ID_SVIP?>" data-bind="click: reservar, html: res_texto, dot: res_titulo, css: {'disabled': is_reserva_disabled}"><b>RESERVA</b> TU CUPO!</a>
                <a class="negativo tp anular" data-placement="right" rel='twipsy' title="Anula tu reserva"  style="display:none;" id_subasta="<?=$smain->ID_SVIP?>" data-bind="click: anular, visible: in_subasta">Anular reserva</a>
                <? } else { ?>
                <a class="btn btn-primary btn-gigante tp" data-placement="left" title="Antes de reservar debes darle Me Gusta a nuestro Facebook" href="https://www.facebook.com/LoKieroBid" target="_blank">Visita nuestro <strong>Facebook</strong></a>
                <? } ?>
            <? } ?>
        <? } else if(!$cp->isLoged) { ?>
            <a class="btn btn-primary btn-gigante tp" href="<?=$cp->loginUrl?>" id="registro2" data-placement="left" title="Usa tu cuenta de Facebook para registrarte!">Ingresa con tu <b>Facebook</b>!</a>
            <div class="fb-facepile" data-width="420" data-max-rows="2" data-size="large"></div>
        <? } ?>
        <? if($smain->ALLOW == 1) { ?>
        <div id="botones" data-bind="fadeVisible: is_visible">    
            <div id="bid_place">
                <a class="btn btn-gigante btn-success tp" id="bid" title="Haz clic para pujar en la subasta!" data-placement="right" data-bind="click: doBid, html: bid_texto, css: {'disabled': is_disabled}">Lo Kiero! (<span id="nBidSub"><?=$smain->BID_RESTO?></span>)</a>
            </div>
            <div id="rec_place" data-bind="fadeVisible: hasRecarga">
                <select class="small_field" name="nBidRec" id="nBidRec">
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                </select>
                <a class="btn tp <?=($smain->RECARGA_RESTO == 0)?"disabled":""?>" id="recarga" title="Te quedan <?=$smain->REGARGA_RESTO?> recargas" data-placement="right" data-bind="click: recarga, html: recarga_texto, css: {'disabled': is_recarga_disabled}">Recarga Bids (<?=$smain->RECARGA_RESTO?>)</a>
            </div>
            <div class="clear"></div>
        </div>
        <? } ?>
        <div data-bind="fadeVisible: showUltimos">
            <h3 style="margin-bottom:5px;">&Uacute;ltimos</h3>
            <ul data-bind="foreach: ultimos" class="ultimos">
                <li><span data-bind="text: $data.HORA_BID_H" class="tiempo"></span> <span data-bind="text: $data.NICK_USUARIO" class="nick"></span></li>
            </ul>
        </div>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<script>
    ko.applyBindings(new SVipViewModel(<?=$smain->ID_SVIP?>, '<?=$smain->COD_SUBASTA?>', <?=(isset($smain->BID_RESTO))?$smain->BID_RESTO:0?>, <?=(isset($smain->RECARGA_RESTO))?$smain->RECARGA_RESTO:0?>, <?=$smain->ESTADO_SUBASTA?>, '<?=$smain->NICK_USUARIO?>', '<?=$smain->RESTO_TIEMPO?>', <?=$smain->RESTO_TIEMPO_SEC?>, <?=$smain->MONTO_SUBASTA?>, <?=($smain->ALLOW==1)?'true':'false'?>));
</script>